apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipeople-anniversary-h5
  labels:
    app: ipeople-anniversary-h5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipeople-anniversary-h5
  template:
    metadata:
      labels:
        app: ipeople-anniversary-h5
    spec:
      containers:
        - name: ipeople-anniversary-h5
          image: 'registry-vpc.cn-shanghai.aliyuncs.com/ab-inbev-apac/ipeople-anniversary-h5:#version_num#'
          # image: 'registry-vpc.cn-shanghai.aliyuncs.com/ab-inbev-apac/ipeople-anniversary-h5:1.0'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # volumeMounts:
          #   - mountPath: /etc/nginx/conf.d/default.conf
          #     name: nginx-config
          #     subPath: abi-default-config.conf
          # subPath: abi-default-web.conf

      # volumes:
      #   - name: nginx-config
      #     configMap:
      #       name: nginx-config
      # serviceAccountName: config-reader
      imagePullSecrets:
        - name: acr-credential-27b7396c3bc51e6df6ffbf8189648a39
